cmake_minimum_required(VERSION 3.14)
project(casca_log_build C)

include(source/CascaLogCMakeUtils.cmake)
if (${CMAKE_BUILD_TYPE} STREQUAL "Debug")
    option(BUILD_CASCA_LOG_TEST_SUITE "CONFIG casca_log_build: enable GoogleTest" ON)
    option(BUILD_CASCA_LOG_TEST_ASAN "CONFIG casca_log_build: enable AddressSanitizer" ON)
else ()
    option(BUILD_CASCA_LOG_TEST_SUITE "CONFIG casca_log_build: enable GoogleTest" OFF)
    option(BUILD_CASCA_LOG_TEST_ASAN "CONFIG casca_log_build: enable AddressSanitizer" OFF)
endif ()
message(STATUS "BUILD casca_log_build: BUILD_CASCA_LOG_TEST_SUITE is set to <${BUILD_CASCA_LOG_TEST_SUITE}>")
message(STATUS "BUILD casca_log_build: BUILD_CASCA_LOG_TEST_ASAN is set to <${BUILD_CASCA_LOG_TEST_ASAN}>")

add_subdirectory(source)
if (BUILD_CASCA_LOG_TEST_SUITE)
    enable_testing()
    add_subdirectory(test)
endif ()