function(casca_log_configure_switch_macro target macro_name description default_value)
    option(BUILD_${macro_name} "CONFIG ${target}: ${description}" ${default_value})
    if (NOT ${BUILD_${macro_name}} MATCHES "^(ON|OFF)$")
        message(FATAL_ERROR "BUILD ${target}: BUILD_${macro_name} value(${BUILD_${macro_name}}) is invalid, it must be ON or OFF")
    endif ()
    if (BUILD_${macro_name})
        target_compile_definitions(${target} PRIVATE ${macro_name}=${BUILD_${macro_name}})
    endif ()
    message(STATUS "BUILD ${target}: ${macro_name} is set to <${BUILD_${macro_name}}>")
endfunction()

function(casca_log_configure_value_macro target macro_name description)
    if (DEFINED ARGV3)
        option(BUILD_${macro_name} "CONFIG ${target}: ${description}" ${ARGV3})
    else ()
        option(BUILD_${macro_name} "CONFIG ${target}: ${description}")
    endif ()
    if (BUILD_${macro_name})
        target_compile_definitions(${target} PRIVATE ${macro_name}=${BUILD_${macro_name}})
        message(STATUS "BUILD ${target}: ${macro_name} is set to <${BUILD_${macro_name}}>")
    else ()
        if (DEFINED ARGV3)
            target_compile_definitions(${target} PRIVATE ${macro_name}=${ARGV3})
            message(STATUS "BUILD ${target}: ${macro_name} is set to default value <${ARGV3}>")
        else ()
            message(STATUS "BUILD ${target}: ${macro_name} is not set")
        endif ()
    endif ()
endfunction()

function(clog_enable_asan_for_target target)
    if (BUILD_CASCA_LOG_TEST_ASAN)
        if (CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
            target_compile_options(${target} PRIVATE
                    -fsanitize=address
                    -fno-omit-frame-pointer
                    -g
                    -O1
            )
            target_link_options(${target} PRIVATE -fsanitize=address)
            message(STATUS "BUILD ${target}: AddressSanitizer is enabled on ${target}")
        else ()
            message(STATUS "BUILD ${target}: AddressSanitizer is not supported on ${target}")
        endif ()
    endif ()
endfunction()